name: Deploy

description: Deliveries - Deploy

inputs:
  app:
    description: App
    required: false
  tier:
    description: Tier
    required: true
  ref:
    description: Ref
    required: false

outputs:
  deployment_url:
    description: The deployed app URL
    value: ${{ steps.deployment_url.outputs.deployment_url }}

runs:
  using: composite
  steps:

    ##############
    # production #
    ##############

    - name: Set deployment url for production
      if: inputs.tier == 'production'
      shell: bash
      run: echo "MANALA_DELIVERIES_DEPLOYMENT_URL=https://share.tom32i.fr" >> $GITHUB_ENV

    ###########
    # staging #
    ###########

    - name: Set deployment url for staging
      if: inputs.tier == 'staging'
      shell: bash
      run: echo "MANALA_DELIVERIES_DEPLOYMENT_URL=https://share.deployer.vm" >> $GITHUB_ENV

    ##########
    # Deploy #
    ##########

    - name: Save deployment url
      id: deployment_url
      shell: bash
      run: echo "deployment_url=${{ env.MANALA_DELIVERIES_DEPLOYMENT_URL }}" >> $GITHUB_OUTPUT

    - name: >
        Deploy
        ${{ inputs.app && format('{0}', inputs.app) || '' }}@${{ inputs.tier }}
      uses: ./.manala/github/integration/run
      with:
        dir: deliveries/${{ inputs.app && format('{0}/', inputs.app) || '' }}${{ inputs.tier }}
        run: |
          make deploy${{ inputs.app && format('.{0}', inputs.app) || '' }}@${{ inputs.tier }} \
            ${{ inputs.ref != '' && format('REF={0}', inputs.ref) || '' }}
