tom32i_showcase:
  path: "%kernel.project_dir%/var/share"
  cache: "%kernel.project_dir%/var/cache/share"
  presets:
    large: { w: 1920, h: 1080, dpr: 1, fit: contain }
    #largeX2: { w: 1920, h: 1080, dpr: 2, fit: contain }
    medium: { w: 1280, h: 720, dpr: 1, fit: contain }
    #mediumX2: { w: 1280, h: 720, dpr: 2, fit: contain }
    small: { w: 960, h: 540, dpr: 1, fit: contain }
    smallX2: { w: 960, h: 540, dpr: 2, fit: contain }
    mobile: { w: 656, h: 369, dpr: 1, fit: contain }
    mobileX2: { w: 656, h: 369, dpr: 2, fit: contain }
    largeWP: { w: 1920, h: 1080, dpr: 1, fit: contain, fm: webp }
    #largeX2WP: { w: 1920, h: 1080, dpr: 2, fit: contain, fm: webp }
    mediumWP: { w: 1280, h: 720, dpr: 1, fit: contain, fm: webp }
    #mediumX2WP: { w: 1280, h: 720, dpr: 2, fit: contain, fm: webp }
    smallWP: { w: 960, h: 540, dpr: 1, fit: contain, fm: webp }
    smallX2WP: { w: 960, h: 540, dpr: 2, fit: contain, fm: webp }
    mobileWP: { w: 656, h: 369, dpr: 1, fit: contain, fm: webp }
    mobileX2WP: { w: 656, h: 369, dpr: 2, fit: contain, fm: webp }
