name: Release
description: Release
author: Elao

inputs:
  secrets:
    description: Secrets
    required: true
  app:
    description: App
    required: false
  tier:
    description: Tier
    required: true
  ref:
    description: Ref
    required: false
  release:
    description: Release
    type: boolean
    default: ${{ github.job == 'release' && 'true' || 'false' }}
  deploy:
    description: Deploy
    type: boolean
    default: ${{ github.job == 'deploy' && 'true' || 'false' }}
  deploy_ref:
    description: Deploy Ref
    required: false
  env:
    description: Env vars as a single string
    required: false
    default: ''

outputs:
  deployment_url:
    description: The deployed app URL
    value: ${{ steps[format('deployment_url_{0}', inputs.tier)].outputs.deployment_url }}

runs:
  using: composite
  steps:

    ##############
    # production #
    ##############

    - name: Checkout production (ref "${{ inputs.ref || 'master' }}")
      if: inputs.tier == 'production'
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref || 'master' }}

    - name: Setup production
      if: inputs.tier == 'production'
      uses: ./.manala/github/system
      with:
        setup: true
        env: ${{ inputs.env }}

    - name: Release production
      if: >
        inputs.tier == 'production'
        && inputs.release != 'false'
      uses: ./.manala/github/system
      with:
        shell_group: 📦 Release
        shell: |
          make release@production \
            AUTHOR="manala-ci-releaser <${{ github.actor }}+github@manala.io>"

    - name: Set deployment URL for production
      if: >
        inputs.tier == 'production'
        && inputs.deploy != 'false'
      id: deployment_url_production
      shell: bash
      run: echo "deployment_url=https://share.tom32i.fr" >> $GITHUB_OUTPUT

    - name: Deploy production
      if: >
        inputs.tier == 'production'
        && inputs.deploy != 'false'
      uses: ./.manala/github/system
      with:
        shell_group: 🚀 Deploy
        shell: |
          make deploy@production \
            ${{ inputs.deploy_ref != '' && format('REF={0}', inputs.deploy_ref) || '' }}

    ###########
    # staging #
    ###########

    - name: Checkout staging (ref "${{ inputs.ref || 'master' }}")
      if: inputs.tier == 'staging'
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref || 'master' }}

    - name: Setup staging
      if: inputs.tier == 'staging'
      uses: ./.manala/github/system
      with:
        setup: true
        env: ${{ inputs.env }}

    - name: Release staging
      if: >
        inputs.tier == 'staging'
        && inputs.release != 'false'
      uses: ./.manala/github/system
      with:
        shell_group: 📦 Release
        shell: |
          make release@staging \
            AUTHOR="manala-ci-releaser <${{ github.actor }}+github@manala.io>"

    - name: Set deployment URL for staging
      if: >
        inputs.tier == 'staging'
        && inputs.deploy != 'false'
      id: deployment_url_staging
      shell: bash
      run: echo "deployment_url=https://share.deployer.vm" >> $GITHUB_OUTPUT

    - name: Deploy staging
      if: >
        inputs.tier == 'staging'
        && inputs.deploy != 'false'
      uses: ./.manala/github/system
      with:
        shell_group: 🚀 Deploy
        shell: |
          make deploy@staging \
            ${{ inputs.deploy_ref != '' && format('REF={0}', inputs.deploy_ref) || '' }}
