services:

    ###########
    # MailHog #
    ###########

    mailhog:
        image: jcalonso/mailhog:v1.0.1
        entrypoint:
            - /MailHog
            - -smtp-bind-addr
            - 0.0.0.0:25
        network_mode: service:app

    #######
    # App #
    #######

    app:
        build:
            args:
                MANALA_PROVISION: ansible
                MANALA_PROVISION_LIMIT: development
        ports:
            # Usuals (Webpack dev-server, …)
            - 2288:8080
            # MailHog
            - 2225:8025
            # Nginx
            - 2280:80
            - 2243:443
