version: "3.8"

volumes:
    app:

services:

    #######
    # App #
    #######

    app:
        volumes:
            # App
            - app:/srv/app

x-mutagen:
    sync:
        defaults:
            configurationBeta:
                permissions:
                    defaultGroup: id:1000
                    defaultOwner: id:1000
                    defaultFileMode: 0644
                    defaultDirectoryMode: 0755
        app:
            alpha: ../..
            beta: volume://app
            mode: two-way-resolved
