services:

    #######
    # App #
    #######

    app:
        build:
            args:
                MANALA_PROVISION: ansible
                MANALA_PROVISION_LIMIT: development
        ports:
            # Usuals (Webpack dev-server, …)
            - 2288:8080
            # Nginx
            - 2280:80
            - 2243:443
