name: Integration
description: Integration
author: Elao

inputs:
  job:
    description: Job
    required: true
    default: ${{ github.job }}
  env:
    description: Env vars as a single string
    required: false
    default: ''

runs:
  using: composite
  steps:

    - name: Setup
      uses: ./.manala/github/system
      with:
        setup: true
        env: ${{ inputs.env }}
