version: '3.5'

volumes:
    mariadb:

services:

    ###########
    # MariaDB #
    ###########

    mariadb:
        hostname: mariadb.Share
        image: mariadb:10.4
        restart: always
        ports:
            - 8306:3306
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project

    ##########
    # System #
    ##########

    system:
        hostname: Share
        build:
            context: .
            target: system
        image: Share:20211003170924
        restart: always
        ports:
            - 8000:80
        volumes:
            - ..:${DIR}
        environment:
            DIR: ${DIR}
            CACHE_DIR: ${CACHE_DIR}
        working_dir: ${DIR}
        entrypoint: .manala/docker/entrypoint
        links:
            - mariadb
