services:

    ###########
    # Mailpit #
    ###########

    mailpit:
        image: axllent/mailpit:v1.21.8
        command:
            - --smtp
            - 0.0.0.0:25
        network_mode: service:app

    #######
    # App #
    #######

    app:
        ports:
            # Mailpit
            - 2225:8025
