services:

    ###########
    # MailHog #
    ###########

    mailhog:
        image: jcalonso/mailhog:v1.0.1
        entrypoint:
            - /MailHog
            - -smtp-bind-addr
            - 0.0.0.0:25
        network_mode: service:app

    #######
    # App #
    #######

    app:
        ports:
            # MailHog
            - 2225:8025
